# Generated by Django 5.2 on 2026-04-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_venta_ventadetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'verbose_name': 'CompraDetalle', 'verbose_name_plural': 'ComprasDetalle'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'verbose_name': 'VentaDetalle', 'verbose_name_plural': 'VentaDetalles'},
        ),
    ]
